name: GitHub Release

on:
  workflow_call:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh release view "$GITHUB_REF_NAME" > /dev/null 2>&1; then
            echo "GitHub Release $GITHUB_REF_NAME already exists"
          else
            gh release create "$GITHUB_REF_NAME" --verify-tag --title "$GITHUB_REF_NAME" \
              --notes-file "release-notes/$GITHUB_REF_NAME.md"
          fi
